version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: biba
      POSTGRES_DB: DocumentsDB
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  users_service:
    container_name: users_service
    build: ./user_service/
    ports:
      - "8000:80"

  documents_service:
    restart: on-failure
    container_name: documents_service
    build: ./document_service/
    ports:
      - "8001:80"
    depends_on:
      - db

  krakend_ce:
    image: devopsfaith/krakend:watch
    volumes:
      - ./config/krakend:/etc/krakend
    platform: linux/amd64
    ports:
      - "8080:8080"
    command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]
    depends_on:
      - users_service
      - documents_service