version: '3.9'

services:
  users_service:
    build: ./user_service/
    ports:
      - 8000:80

  documents_service:
    build: ./document_service/
    ports:
      - 8001:80

  krakend_ce:
    image: devopsfaith/krakend:watch
    volumes:
      - ./config/krakend:/etc/krakend
    platform: linux/amd64
    ports:
      - "8080:8080"
    command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]
    depends_on:
      - users_service
      - documents_service