name: CI/CD pipeline

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:


jobs:
  build_and_push_user_service:
    name: Build and push user service to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          cd user_service && docker build -f Dockerfile . -t ${{ secrets.DOCKER_USERNAME }}/ms-user-services:latest 

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push tag to docker hub
        run: | 
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest